/*
 * RadarGUI.java
 *
 * Created on 4. Juni 2007, 23:59
 */

package radarwonline;

//import com.jgoodies.looks.plastic.PlasticLookAndFeel;
import java.awt.Image;
import java.io.*;
import java.net.*;
import java.net.URL;
import java.util.Date;
import javax.swing.*;
import com.digitprop.tonic.TonicLookAndFeel;
import javax.swing.UnsupportedLookAndFeelException;
import net.sourceforge.napkinlaf.NapkinLookAndFeel;

/**
 *
 * @author  finke
 */
public class RadarGUI1 extends javax.swing.JFrame {
    
    /** Creates new form RadarGUI */
    public RadarGUI1() {
         try {
           //  UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
           // UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
           //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
            //UIManager.setLookAndFeel(new PlasticLookAndFeel());
            //UIManager.setLookAndFeel(new WindowsLookAndFeel());
             UIManager.setLookAndFeel(new TonicLookAndFeel());
            //UIManager.setLookAndFeel(new NapkinLookAndFeel());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (UnsupportedLookAndFeelException ex) {}
         catch (Exception e){}
        initComponents();
        //ImageIcon ii = new ImageIcon("c:/_/fd.jpg");
        
        setIconImage(new ImageIcon("fd.jpg").getImage());
        //getShopFrame().setIconImage(Image);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbPic = new javax.swing.JLabel();
        btExit = new javax.swing.JButton();
        btGet = new javax.swing.JButton();
        lbOk = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Das Aktuelle Radar-Bild von Wetter-Online.de");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DWD-Radar"));

        lbPic.setIcon(new javax.swing.ImageIcon("C:\\2215.gif")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbPic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        btGet.setText("Get");
        btGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGetActionPerformed(evt);
            }
        });

        lbOk.setText("ok");
        lbOk.setToolTipText("(cc) U. Finke");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btGet)
                                .addGap(50, 50, 50)
                                .addComponent(lbOk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                                .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btExit, btGet});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExit)
                    .addComponent(btGet)
                    .addComponent(lbOk))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGetActionPerformed
     String s=getNewRadarPic();
     lbPic.setIcon(new ImageIcon("c:/"+s));
    // try{
    //   lbPic.setIcon(new ImageIcon(new URL("http://www.wetteronline.de/daten/radar/dnie/2007/12/20/2015.gif")));
    // }
    // catch (MalformedURLException e){}
    }//GEN-LAST:event_btGetActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
     System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadarGUI1().setVisible(true);
            }
        });
    }
    
    //gibt datumsabh�ng. pfad und namen der datei zur�ck
    private String[] generateName() {
        String[] s = new String[2];
        Date date = new Date();
    //10 min zur�cksetzen auserdem -2std
        long tt=date.getTime()-(2L*60+10)*60*1000;
        Date ndate=new Date(tt);
        int mn=ndate.getMinutes();
    //runden auf volle 15-ner
        mn=(mn/15)*15;

        s[0]=String.format("%1$tY/%1$tm/%1$td/",ndate);
        s[1]=String.format("%1$tH%2$02d",ndate,mn)+".gif";
        return s;
    }
    
    public String getNewRadarPic()
	{
          String dName="";
	  byte[] buff=new byte[100000];  
	  try{ 
	      String[] s=generateName();
              String dPfad=s[0];
              dName=s[1];

    	      URL addr = new URL("http://www.wetteronline.de/daten/radar/dnie/"+dPfad+dName);
	      BufferedInputStream in = new BufferedInputStream(
				addr.openStream()); 
				
	      BufferedOutputStream out=new BufferedOutputStream(
		       new FileOutputStream("c:/"+dName));
		       
              int len=in.read(buff) ; 
              while (len!=-1) {
               out.write(buff,0,len);     
               len=in.read(buff);
              } 
	      out.close();
	      in.close();
	      lbOk.setText(dName);  	
	   }
	   catch (MalformedURLException eurl){lbOk.setText(eurl.getMessage());}
	   catch (IOException eio){lbOk.setText(eio.getMessage());}
          return dName;
     }   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExit;
    private javax.swing.JButton btGet;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lbOk;
    private javax.swing.JLabel lbPic;
    // End of variables declaration//GEN-END:variables
    
}
